apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dHVfcGFzc3dvcmRfc2VndXJv  # "tu_password_seguro" en base64
  MYSQL_DATABASE: bWlfZGI=                       # "mi_db" en base64
  MYSQL_USER: dXN1YXJpbw==                       # "usuario" en base64
  MYSQL_PASSWORD: cGFzc3dvcmRfdXN1YXJpbw==       # "password_usuario" en base64