apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx
spec:
  replicas: 2  # Escalable
  selector:
    matchLabels:
      app: php-nginx
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
      - name: php
        image: php:8.1-fpm
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: app-code
        configMap:
          name: app-code
      - name: nginx-config
        configMap:
          name: nginx-config