apiVersion: v1
kind: Service
metadata:
  name: php-nginx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: php-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80  # Cambiado de 9090 a 80
      nodePort: 30080