apiVersion: v1
kind: Service
metadata:
  name: php-nginx-service
spec:
  type: NodePort  # Para acceder desde fuera
  selector:
    app: php-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30080  # Puerto accesible en el nodo (rango 30000-32767)